# Generated by Django 5.1.4 on 2025-03-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='faces_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='vertices_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
