# Generated by Django 5.1.4 on 2025-03-03 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_analysisresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='detected_defects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.modelfile'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20),
        ),
    ]
