# Generated by Django 5.1.4 on 2025-03-03 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_analysisresult_detected_defects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
