# Generated by Django 5.1.4 on 2025-03-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_modelfile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfile',
            name='created_at',
        ),
    ]
