# Generated by Django 5.1.4 on 2025-03-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_defect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='model',
        ),
        migrations.CreateModel(
            name='DefectAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50)),
                ('report_path', models.CharField(blank=True, max_length=500, null=True)),
                ('defect_count', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, null=True)),
                ('model_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='myapp.modelfile')),
            ],
        ),
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
        migrations.DeleteModel(
            name='Defect',
        ),
    ]
