# Generated by Django 5.1.4 on 2025-03-11 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_defect_model_defectanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='pdf', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('defect_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='myapp.defectanalysis')),
            ],
        ),
    ]
