# Generated by Django 5.1.4 on 2025-03-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_modelfile_uploaded_at_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectanalysis',
            name='is_watertight',
            field=models.BooleanField(default=False),
        ),
    ]
