# Generated by Django 5.1.4 on 2025-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_defectanalysis_defect_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectanalysis',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
